# Generated by Django 5.2 on 2025-04-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafdiseasedetector',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leafdiseasedetector',
            name='disease',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leafdiseasedetector',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
